export const RECEIVE_TEAMINFO_SUCCESS = 'RECEIVE_TEAMINFO_SUCCESS';
export const RECEIVE_TEAMINFO_FAIL = 'RECEIVE_TEAMINFO_FAIL';
export const FETCHING_TEAMINFO_REQUEST = 'FETCHING_TEAMINFO_REQUEST';
// export const UPDATE_PAGE = 'UPDATE_PAGE';